version: '4.29.0'

services:
  expense_tracker:
    container_name: expense_tracker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    networks:
      - laravel

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: expense_tracker
      MYSQL_PASSWORD: root1234
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
